/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

tensor(310.7826)
tensor(310.7826)
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 2): env://, gpu 2
Traceback (most recent call last):
Traceback (most recent call last):
  File "main_ltrp.py", line 328, in <module>
  File "main_ltrp.py", line 328, in <module>
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608614 closing signal SIGINT
    main(args)
  File "main_ltrp.py", line 130, in main
  File "main_ltrp.py", line 130, in main
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608615 closing signal SIGINT
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608616 closing signal SIGINT
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608617 closing signal SIGINT
  File "/home/s2/youngjoonjeong/github/ltrp/utils/misc.py", line 245, in init_distributed_mode
    misc.init_distributed_mode(args)
  File "/home/s2/youngjoonjeong/github/ltrp/utils/misc.py", line 245, in init_distributed_mode
Traceback (most recent call last):
  File "main_ltrp.py", line 24, in <module>
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 627, in init_process_group
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 627, in init_process_group
    from utils.datasets import ImageNetSubset
  File "/home/s2/youngjoonjeong/github/ltrp/utils/datasets.py", line 16, in <module>
        _store_based_barrier(rank, store, timeout)
_store_based_barrier(rank, store, timeout)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 241, in _store_based_barrier
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 241, in _store_based_barrier
    time.sleep(0.01)    
time.sleep(0.01)
KeyboardInterrupt
KeyboardInterrupt
    from timm.data import create_transform
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/models/__init__.py", line 1, in <module>
    from .beit import *
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/models/beit.py", line 32, in <module>
    from .vision_transformer import checkpoint_filter_fn
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 35, in <module>
    from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD, IMAGENET_INCEPTION_MEAN, IMAGENET_INCEPTION_STD
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/data/__init__.py", line 5, in <module>
    from .dataset import ImageDataset, IterableImageDataset, AugMixDataset
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/data/dataset.py", line 12, in <module>
    from .parsers import create_parser
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/data/parsers/__init__.py", line 1, in <module>
    from .parser_factory import create_parser
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/data/parsers/parser_factory.py", line 3, in <module>
    from .parser_image_folder import ParserImageFolder
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/data/parsers/parser_image_folder.py", line 10, in <module>
    from timm.utils.misc import natural_key
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/utils/__init__.py", line 13, in <module>
    from .summary import update_summary, get_outdir
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/timm/utils/summary.py", line 9, in <module>
    import wandb
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/wandb/__init__.py", line 22, in <module>
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608614 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608615 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608616 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 608617 closing signal SIGTERM
Traceback (most recent call last):
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 608575 got signal: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 716, in run
    self._shutdown(e.sigval)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 193, in _shutdown
    self._pcontext.close(death_sig)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 330, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 707, in _close
    handler.proc.wait(time_to_wait)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/subprocess.py", line 1816, in _wait
    time.sleep(delay)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 608575 got signal: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 721, in run
    self._shutdown()
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/local_elastic_agent.py", line 193, in _shutdown
    self._pcontext.close(death_sig)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 330, in close
    self._close(death_sig=death_sig, timeout=timeout)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 707, in _close
    handler.proc.wait(time_to_wait)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/subprocess.py", line 1816, in _wait
    time.sleep(delay)
  File "/home/s2/youngjoonjeong/anaconda3/envs/LTRP/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 608575 got signal: 2
